### ISSUE TITLE
Fix velocity update during correction step

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/cfd-mini-app#25]
See lines:

https://github.com/DARMA-tasking/cfd-mini-app/blob/6760f95996e153db0d840636944dbdafc8ce216c/cppfd/solver.cpp#L349-L356

Currently the correction is asymmetrical because it is only using pressure contributions from the top and right cells (not from the lower left).

**Comment by ppebay** [comment]
In order to make the correction symmetrical:
* the `u` component of `velocity` should also be corrected with the `pressure` values of the 2 cells below it (currently only the 2 above are used);
* the `v` component of `velocity` should also be corrected with the `pressure` values of the 2 cells to left of it (currently only the 2 to the right are used).
