### ISSUE TITLE
Fix index bounds in predictor step

### ISSUE THREAD

**Issue by pierrepebay** [DARMA-tasking/cfd-mini-app#38]
<img width="1323" alt="Screenshot 2021-10-04 at 08 40 31" src="https://user-images.githubusercontent.com/68857547/135805135-2630b467-ea10-4a76-be0a-74b6c27c8027.png">
m and n are initialised 1 int to low

**Comment by ppebay** [comment]
I don't understand the issue here.
In the original code we have:
* `j` varying from 1 (included) to `n_points_y - 1` (excluded)
* `i` varying from 1 (included) to `n_points_x - 1` (excluded)

In the new code we have
* `j` varying from 1 (included) to `nm1` (excluded)
* `i` varying from 1 (included) to `mm1` (excluded)
with:
* `nm1 = n_points_y - 1`
* `mm1 = n_points_x - 1`
and therefore:
* `j` varying from 1 (included) to `n_points_y-1` (excluded)
* `i` varying from 1 (included) to `n_points_x-1` (excluded)

So where is the difference?
@pierrepebay

**Comment by pierrepebay** [comment]
the problem comes from the fact that nnm1 and mm1 are initialized through m and n, which are the variables that aren't correctly set:
- `m = n_points_x - 1`
- `n = n_points_y - 1`
this should be:
- `m = n_points_x`
- `n = n_points_y`
